[package]
name = "nannou-project"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "circle-packing",
]

[dependencies]
nannou = "0.18"

[[bin]]
name = "circle-packing"
path = "./circle-packing/src/main.rs"
